import puppeteer from "puppeteer-core";
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const b=await puppeteer.launch({executablePath:"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",headless:"new",userDataDir:`/tmp/gr-scroll-${process.pid}`,args:["--no-first-run","--font-render-hinting=none"]});
const p=await b.newPage(); await p.setViewport({width:520,height:1000,deviceScaleFactor:3});
const problems=[]; p.on("pageerror",e=>problems.push(e.message.slice(0,120)));
p.on("console",m=>{if(m.type()==="error")problems.push(m.text().slice(0,120))});
await p.goto("http://127.0.0.1:4825",{waitUntil:"networkidle0"}); await wait(800);
await p.evaluate(()=>{const el=document.querySelector(".screen-scroll"); el.scrollTop = el.scrollHeight;});
await wait(600);
await (await p.$(".screen")).screenshot({path:"shots/today-bottom.png"});
console.log(problems.length?problems.join("\n"):"clean");
await b.close();
